version: '3.8'
services:
  movies:
    image: pradeep332/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: pradeep332/paytmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  
  recharge:
    image: pradeep332/paytmrecharge:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
