version: '3.8'
services:
  movies:
    image: pnegi5106/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: pnegi5106/paytmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  
  recharge:
    image: pnegi51063/paytmrecharge:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
